version: "3"
services:
  tettitori-api:
    container_name: tettitori-api
    build: ./tettitori-api
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mongodb://mongodb:27017
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      PORT: 8080
    depends_on:
      - mongodb
    volumes:
      - "./attachments:/opt/tettitori-api/attachments"
      - "./api-logs:/opt/tettitori-api/logs"
    networks:
      - mynet

  tettitori-ui:
    container_name: tettitori-ui
    build: ./tettitori-ui
    ports:
      - "80:3000"
    volumes:
      - "./ui-logs:/opt/tettitori-ui/logs"
    networks:
      - mynet

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27107"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./mongodb:/data/db"
    networks:
      - mynet
networks:
  mynet:
